Feature OIDC integration
AtlasOfLivingAustralia/alerts pull request #154
Opened 2022-05-16 00:11 UTC by yasima-csiro

2022-05-16 23:37 UTC, Rita-C requested changes

2022-05-16 23:37 UTC, Rita-C commented on grails-app/services/au/org/ala/alerts/UserService.groovy
> +@Slf4j
Do we need `Slf4j`? cannot use default `log`?

2022-05-16 23:37 UTC, Rita-C commented on grails-app/services/au/org/ala/alerts/UserService.groovy
> +//    @Cacheable("testCache")
Please delete unused code

2022-05-16 23:37 UTC, Rita-C commented on src/test/groovy/au/org/ala/alerts/UnsubscribeControllerSpec.groovy
> +@Slf4j
Slf4j?

2022-05-17 23:01 UTC, yasima-csiro commented on build.gradle
> +        classpath 'org.grails.plugins:quartz:2.0.13'
This is because Gradle 5 has stopped pulling in transitive dependancies. So, this is a workaround for that. https://stackoverflow.com/questions/61144025/quartz-not-working-in-grails4-issue-in-dependency-not-able-to-compile

2022-05-17 23:06 UTC, yasima-csiro commented on grails-app/services/au/org/ala/alerts/NotificationService.groovy
> +@Slf4j
Slf4j is the new default. "The log property injected at compile time into all classes is now an Slf4j Logger instance and not an instance of the Commons Logging Log class." So, had to use that.
https://grails.github.io/grails-upgrade/latest/guide/index.html#upgrading31x

2022-05-17 23:23 UTC, Rita-C commented on build.gradle
> +        classpath 'org.grails.plugins:quartz:2.0.13'
There are two `org.grails.plugins:quartz:2.0.13` entries in `build.gradle`, is that required?

2022-05-17 23:29 UTC, Rita-C commented on grails-app/services/au/org/ala/alerts/NotificationService.groovy
> +@Slf4j
Understand the default Logger. I thought you don't need to add `@Slf4j` or the import statement here.

2022-05-17 23:39 UTC, yasima-csiro commented on grails-app/services/au/org/ala/alerts/UserService.groovy
> +//    @Cacheable("testCache")
This method stopped working once the app was migrated to grails 4. I am not sure how to fix that. Alerts team might need to look into that.

2022-05-17 23:53 UTC, yasima-csiro commented on build.gradle
> +        classpath 'org.grails.plugins:quartz:2.0.13'
yes, first entry needs to compile all the job classes. Otherwise compile will fail. This is an issue in quarts plugin. This is the workaround to fix that.

2022-05-17 23:54 UTC, yasima-csiro commented on grails-app/services/au/org/ala/alerts/NotificationService.groovy
> +@Slf4j
I will check that.

2022-05-18 00:12 UTC, yasima-csiro commented on grails-app/services/au/org/ala/alerts/NotificationService.groovy
> +@Slf4j
Yes, you are correct. We can skip the annotation and import in controllers and service classes.

2022-05-18 00:15 UTC, yasima-csiro commented on build.gradle
> +        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:3.0.10"
Fixed.

2022-05-18 00:15 UTC, yasima-csiro commented on build.gradle
> +    runtime 'org.ehcache:ehcache'
Removed.

2022-05-18 00:15 UTC, yasima-csiro commented on gradle.properties
> +gormVersion=7.0.2
Fixed.

2022-05-18 00:15 UTC, yasima-csiro commented on grails-app/services/au/org/ala/alerts/NotificationService.groovy
> +@Slf4j
Fixed.

2022-05-18 00:16 UTC, yasima-csiro commented on grails-app/services/au/org/ala/alerts/UserService.groovy
> +@Slf4j
Fixed.

2022-05-18 00:37 UTC, yasima-csiro commented on src/test/groovy/au/org/ala/alerts/UnsubscribeControllerSpec.groovy
> +@Slf4j
This needs to create a logger instance.

2022-05-19 00:20 UTC, Rita-C commented on grails-app/services/au/org/ala/alerts/UserService.groovy
> +//    @Cacheable("testCache")
Update `ehcache3.xml`?
fieldcapture and lists have `ehcache` working

2022-05-24 04:17 UTC, Rita-C approved these changes

2022-05-25 01:06 UTC, Rita-C commented on grails-app/conf/application.yml
> +        discoveryUri: https://auth-dev.ala.org.au/cas/oidc/.well-known
use `auth-test` since code has been deployed to test?

2022-05-25 01:07 UTC, Rita-C approved these changes
Approved with one new comment.

2022-05-25 01:08 UTC, yasima-csiro commented on grails-app/conf/application.yml
> +        discoveryUri: https://auth-dev.ala.org.au/cas/oidc/.well-known
sure will change this.

2022-05-25 05:53 UTC, yasima-csiro commented on grails-app/services/au/org/ala/alerts/UserService.groovy
> +//    @Cacheable("testCache")
Fixed

2022-05-31 00:23 UTC, Rita-C approved these changes

2022-06-01 22:10 UTC, merged