BioSecurity Email Template
AtlasOfLivingAustralia/alerts pull request #192
Opened 2024-02-11 22:58 UTC by qifeng-bai

2024-02-12 22:16 UTC, yasima-csiro approved these changes

2024-04-16 04:57 UTC, adam-collins requested changes
Changes requested.

2024-04-16 04:57 UTC, adam-collins commented on grails-app/conf/application.yml
> +        userDetails:
Should be lowercase `userdetails`

2024-04-16 04:57 UTC, adam-collins commented on grails-app/conf/application.yml
> +        userDetails:
Should be lowercase `userdetails`

2024-04-16 04:57 UTC, adam-collins commented on grails-app/conf/application.yml
> +        userDetails:
Should be lowercase `userdetails`

2024-04-16 04:57 UTC, adam-collins commented on grails-app/controllers/au/org/ala/alerts/AdminController.groovy
> +            def query = Query.get(14)
Search for the correct ID for query and frequency instead of using a static value.

2024-04-16 04:57 UTC, adam-collins commented on grails-app/controllers/au/org/ala/alerts/AdminController.groovy
> +            QueryResult qr = notificationService.getQueryResult(query, frequency)
`qr` is assigned and never used.

2024-04-16 04:57 UTC, adam-collins commented on grails-app/controllers/au/org/ala/alerts/AdminController.groovy
> +            unsubscribeOneUrl = grailsApplication.config.grails.serverURL + "/unsubscribe?token=${unsubscribeToken}"
Elsewhere in this function `urlPrefix`. This line uses `grails.serverURL`. Only one method to get the url should be used.

2024-04-16 04:57 UTC, adam-collins commented on grails-app/controllers/au/org/ala/alerts/WebserviceController.groovy
> +    def getQueryLogs() {
Add authentication

2024-04-16 04:57 UTC, adam-collins commented on grails-app/controllers/au/org/ala/alerts/WebserviceController.groovy
> +    def searchSubscriptions() {
add authentication

2024-04-16 04:57 UTC, adam-collins commented on grails-app/controllers/au/org/ala/alerts/WebserviceController.groovy
> +    def getSubscribers() {
add authentication

2024-04-16 04:57 UTC, adam-collins commented on grails-app/controllers/au/org/ala/alerts/WebserviceController.groovy
> +    def addSubscribers() {
add authentication

2024-04-16 04:57 UTC, adam-collins commented on grails-app/controllers/au/org/ala/alerts/WebserviceController.groovy
> +    def unsubscribe() {
Add authentication and rename to distinguish from the user unsubscribe URL.

2024-04-16 04:57 UTC, adam-collins commented on grails-app/controllers/au/org/ala/alerts/WebserviceController.groovy
> +    def triggerBiosecurityAlerts () {
Add authentication

2024-04-16 04:57 UTC, adam-collins commented on grails-app/controllers/au/org/ala/alerts/WebserviceController.groovy
> +    def triggerBiosecurityAlert (int id) {
Add authentication

2024-04-16 04:57 UTC, adam-collins commented on grails-app/controllers/au/org/ala/alerts/WebserviceController.groovy
> +    def triggerBiosecurityAlertSince (int id) {
add authentication

2024-04-16 04:57 UTC, adam-collins commented on grails-app/services/au/org/ala/alerts/NotificationService.groovy
> +    def triggerSubscription(Query query) {
This function is only for biosecurity alerts. Rename to indicate this.

2024-04-16 04:57 UTC, adam-collins commented on grails-app/services/au/org/ala/alerts/NotificationService.groovy
> +    def triggerSubscription(Query query, Date since) {
This function is only for biosecurity alerts. Rename to indicate this.

2024-04-16 04:57 UTC, adam-collins commented on grails-app/services/au/org/ala/alerts/NotificationService.groovy
> +                [email: user.email, userUnsubToken: user.unsubscribeToken, notificationUnsubToken: notificationUnsubToken]
There looks to be a change of the unsubscribe token retrieval. Have the unsubscribe links been tested?

2024-04-16 04:57 UTC, adam-collins commented on grails-app/services/au/org/ala/alerts/NotificationService.groovy
> +            result = [status: 1, message: "Failed to trigger subscription [ ${query?.id}  ${query?.name} ]" + e.message]
This deletes any prior `result.logs`.

2024-04-16 04:57 UTC, adam-collins commented on grails-app/domain/au/org/ala/alerts/QueryResult.groovy
> +    String getQueryUrlUIUsed() {
Is this used anywhere?

2024-04-16 04:57 UTC, adam-collins commented on grails-app/services/au/org/ala/alerts/QueryService.groovy
> +    def searchSubscriptions(keywords) {
This is only for biosecurity alerts. Rename to indicate this.

2024-04-16 05:07 UTC, qifeng-bai commented on grails-app/conf/application.yml
> +        userDetails:
Done

2024-04-16 05:07 UTC, qifeng-bai commented on grails-app/conf/application.yml
> +        userDetails:
done

2024-04-16 05:07 UTC, qifeng-bai commented on grails-app/conf/application.yml
> +        userDetails:
changed

2024-04-16 05:10 UTC, qifeng-bai commented on grails-app/controllers/au/org/ala/alerts/AdminController.groovy
> +            def query = Query.get(14)
It is written in 2017 for testing if an email can be sent.  I removed it since we Biosecurity Admin has this bit function

2024-04-16 05:13 UTC, qifeng-bai commented on grails-app/services/au/org/ala/alerts/NotificationService.groovy
> +                [email: user.email, userUnsubToken: user.unsubscribeToken, notificationUnsubToken: notificationUnsubToken]
Yes, it has been tested

2024-04-16 05:15 UTC, qifeng-bai commented on grails-app/services/au/org/ala/alerts/NotificationService.groovy
> +    def triggerSubscription(Query query, Date since) {
Changed

2024-04-16 05:17 UTC, qifeng-bai commented on grails-app/domain/au/org/ala/alerts/QueryResult.groovy
> +    String getQueryUrlUIUsed() {
Yes, it is passed to templates to display the query url if need

2024-04-16 05:19 UTC, qifeng-bai commented on grails-app/services/au/org/ala/alerts/QueryService.groovy
> +    def searchSubscriptions(keywords) {
Changed

2024-04-16 23:31 UTC, qifeng-bai commented on grails-app/controllers/au/org/ala/alerts/AdminController.groovy
> +            QueryResult qr = notificationService.getQueryResult(query, frequency)
Removed

2024-04-16 23:43 UTC, qifeng-bai commented on grails-app/controllers/au/org/ala/alerts/AdminController.groovy
> +            unsubscribeOneUrl = grailsApplication.config.grails.serverURL + "/unsubscribe?token=${unsubscribeToken}"
Using grails.serverURL now, instead of security.cas.appServerName

2024-06-27 00:29 UTC, closed without merging